apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-devops-world
  labels:
    app: python-hello-devops-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-hello-devops-world
  template:
    metadata:
      labels:
        app: python-hello-devops-world
    spec:
      containers:
      - name: python-hello-devops-world
        image: mgsantos89/python_hello-devops-world:v1  
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-hello-devops-world-service
spec:
  selector:
    app: python-hello-devops-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: python-hello-devops-world-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#  - host: python-hello-devops-world.example.com  # Substitua pelo seu domínio ou IP público
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: python-hello-devops-world-service
#            port:
#              number: 80
#